triggers = {
    "real" : "REAL SO REAL WOAHHH WOAHHH THEY THINK IM MADE OF STEEL WOAH WOAH",
    "portug" : ":flag_pt: PORTUGAL MENTIONED :fire: PASTEL DE NATA :fish: BACALHAU :soccer: CRISTIANO RONALDO :chart_with_downwards_trend: WTF IS AN EFFICIENT GOVERNMENT :flag_pt:",
    "olanda" : "<:iolandajudge:1231254926961676321>",
    #"<@1252795706188496906>" : "no ping pls im eepy",
    "merica" : "https://i.kym-cdn.com/photos/images/original/002/215/142/0b9.gif",
    "cypr" : "https://tenor.com/view/cyprus-watermelon-gif-27408453",
    "toil" : "After my several decades of service to the NBU, my back hurts from the breaking pain of leaning over to my device, picking up my Apple Pencil, my knuckles cracking in misery, with tears dropping at each line of drawing I do, and keeping this servers head on with a soul decaying dignity, constant demands for design. Someone kill me. The budget at the NBU is terrible. There is no toilet. Their toilet fucking broke.",
    "anx" : "WOAHHHHHHHHH OHHHHH",
    "math" : "*meth",
    "trol" : "You've been trolled, you've been trolled Yes, you've probably been told Don't reply to this guy He's just trying to get a rise Out of you, yes, it's true You respond and that's his cue To start trouble on the double While he strokes his manly stubble",
    "bab" : "bejba\n\nit's kinda krejzah",
    "grit" : "grito more like midto",
    "mod" : "mods? you mean NBU ~~wage slaves~~ employees and ~~unpaid interns~~ associates?",
    #"see" : "it is time to open up your nose",
    "craz" : "Crazy? I was crazy once. They put me in a room. A rubber room. A rubber room with rats. And rats make me crazy.",
    "1984" : "Democracy? What's that? We are an authoritarian 1984 dystopian Orwell server",
    "brok" : "woah oh oh",
    "going back" : "WOAHHHHHHHHH OHHHHH",
    "to black" : "WOAHHHHHHHHH OHHHHH",
    #"can you see" : "this is badvision ofc i cant see",
    "los" : "Nah, I'd win",
    "chin" : "Apply for Chinese citizenship 🇨🇳🇨🇳🇨🇳🇨🇳🧧🥡🥢🥠🥮🗣️🗣️🗣️🗣️🔈🔈🔈",
    "kys" : ":rage: :sob:",
    "stfu" : "ad hominem",
    "spawn" : "how bout you spawn some bitches",
    "spown" : "how bout you spown some bitches",
    "monad" : "A monad is a monoid in the category of endofunctors"
    }
